name: lstm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow==2.13.0
      - keras==2.13.1
      - numpy==1.24.3
      - opencv-python
      - streamlit
